#if !canImport(ObjectiveC)
import XCTest

extension ConsoleColorDemoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConsoleColorDemoTests = [
        ("testExecutable", testExecutable),
        ("testExecutableNoInput", testExecutableNoInput),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ConsoleColorDemoTests.__allTests__ConsoleColorDemoTests),
    ]
}
#endif
