#if !canImport(ObjectiveC)
import XCTest

extension ConsoleColorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConsoleColorTests = [
        ("testAddFormatSimple", testAddFormatSimple),
        ("testAddFormatSimpleWithNoReset", testAddFormatSimpleWithNoReset),
        ("testAddMultipleFormats", testAddMultipleFormats),
        ("testAddMultipleFormatsWithNoReset", testAddMultipleFormatsWithNoReset),
        ("testClearFormat", testClearFormat),
        ("testNoResetWithResetAlreadyInInput", testNoResetWithResetAlreadyInInput),
    ]
}

extension EightBitColorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EightBitColorTests = [
        ("testInputLessThan0", testInputLessThan0),
        ("testInputOver255", testInputOver255),
        ("testNormalInput", testNormalInput),
    ]
}

extension ExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExtensionsTests = [
        ("testApplyCCFormatEightBitColor", testApplyCCFormatEightBitColor),
        ("testApplyCCFormatSimpleColor", testApplyCCFormatSimpleColor),
        ("testApplyingCCFormatEightBitColor", testApplyingCCFormatEightBitColor),
        ("testApplyingCCFormatSimpleColor", testApplyingCCFormatSimpleColor),
        ("testClearFormat", testClearFormat),
        ("testClearingCCFormat", testClearingCCFormat),
        ("testStackedApplies", testStackedApplies),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ConsoleColorTests.__allTests__ConsoleColorTests),
        testCase(EightBitColorTests.__allTests__EightBitColorTests),
        testCase(ExtensionsTests.__allTests__ExtensionsTests),
    ]
}
#endif
